### PR TITLE
Add task header for "Add a domain" task

### LINKED ISSUE #1008: Free trial: Create task header component for "Add a domain" task
Task header for `Add a domain` needs to be built

## User Story

> As a free trial user, 
> I want to see task header when the current task is `Add a domain`
> so that I'm informed of what the task is about

## Acceptance Criteria

```
Feature: `Add a domain` header
Given the user is on a free trial plan
When the user views WooCommerce homescreen
Then show task header
```

Image

Figma: lD0gTB4IqGsmSmsnjZNaP6-fi-278%3A10816

### PR DESCRIPTION
**Pull request by chihsuan**
### Changes proposed in this Pull Request:

Closes #1008.

Add task header for "Add a domain" task. Note that this change is for all plans.

Screenshot 2023-03-02 at 12 02 35

Figma: lD0gTB4IqGsmSmsnjZNaP6-fi-278%3A10816

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Go to `WooCommerce > Home`
2. Complete all tasks except "Add a domain" task
3. Confirm "Add a domain" task has a task header, and it matches the design
4. Click on "Add a domain" button
5. You should be navigated to domain page.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Looking good so far, @chihsuan! It seems the `add-domain-illustration.png` is quite low resolution. Can we re-export from figma with higher resolution, or as SVG?

**Comment by ilyasfoo** [comment]
Group 1000004630 4x

I managed to export 4x

**Comment by chihsuan** [comment]
> Actually, let's use 2x

Sounds good. Updated in 6d1f5c47ce17eb8468b9f3cc0765ab7d3a9c72a2.

**Review by rjchow — APPROVED** [review]
nice work, tests well!

**Review by ilyasfoo — APPROVED** [review]
Thanks for fixing, LGTM!

**Pull request merged**
