### PR TITLE
Enable cys feature flag

### LINKED ISSUE #1305: Turn on CYS feature flag and hide "Choose Your Theme" task
**Issue Description:**

Turn on CYS feature flag (`customize-store`) and remove ["Choose Your Theme" task](https://github.com/Automattic/wc-calypso-bridge/blob/7f8f4b9038634f3df4220b1dc87c8fa32276856f/includes/tasks/class-wc-calypso-task-appearance.php#L29) to launch CYS MVP on WooExpress.

### PR DESCRIPTION
**Pull request by chihsuan**
### Changes proposed in this Pull Request:

Closes #1305.

 Enable customize-store feature flag.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Set up a Woo Express testing site: p6q8Tx-3Je-p2 (Do not turn on CYS feature flag via beta tester)
2. Go to Homescreen
2. Observe `Choose your theme` task in tasklist
3. Run `option set woocommerce_admin_install_timestamp 1704254400 `
4. Go to Homescreen
5. Observe that `Customize your store` task is shown

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
Tests well!

**Review by adrianduffell — APPROVED** [review]
LGTM 🚀

**Comment by ilyasfoo** [comment]
@chihsuan It looks like this PR is going to be superseded by an ExPlat condition. I think we can close this one. Thanks for preparing this PR though!

**Comment by chihsuan** [comment]
> @chihsuan It looks like this PR is going to be superseded by an ExPlat condition. I think we can close this one. Thanks for preparing this PR though!
> 
> Edit: Actually, this might still be useful when we're to deploy 100%. Perhaps we could just add experiment removal code. Nevermind my comment!

@ilyasfoo Haha, then I'll keep this PR open. Thank you!

**Comment by ilyasfoo** [comment]
@chihsuan  Looks like we're going without ExPlat p1702940957786639-slack-C053716F2H2

This PR should be sufficient 👍

**Review by ilyasfoo — APPROVED** [review]
Tested again with the timestamp, works well! 🚢

**Pull request merged**
