### PR TITLE
Free trial: Update notice messages and other copies

### LINKED ISSUE #1019: Free trial: Update notice messages and other copies
We need to update free trial notices to reflect latest changes from p1677673565835379/1677509212.632429-slack-CNA89KY6M.

#### Free trial notices

Figma: lD0gTB4IqGsmSmsnjZNaP6-fi-49%3A7986

- **Payments task:** Only Administrators and Store Managers can place orders during the free trial. If you are ready to accept payments from customers, [upgrade to a paid plan](url).
- **Tax task (New notice, I've missed it before):** During the free trial period you can configure your sales tax settings, but not collect it. To start selling products, [upgrade now](url).

Figma: 1EGipzzulCg2uk4MsSf2x7-fi-14%3A7215

- **WCPay welcome screen, WCPay overview screen:** Only Administrators and Store Managers can place orders during the free trial. If you are ready to accept payments from customers, [upgrade to a paid plan](url).
- **WCPay transactions screen:** Only Administrators and Store Managers can place orders during the free trial. If you are ready to accept payments from customers, [upgrade to a paid plan](url).
 - **WCPay deposits screen:** Deposits are not available during the trial period. To start processing real transactions and receive payments and payouts, [upgrade to a pain plan](url).

#### Payments task fill header

- Get ready to accept payments

#### Payments task header description

- Give your customers an easy and convenient way to pay! Set up and test some of our fast and secure online or in person payment methods.

### Acceptance criteria

1. Update all copies from latest changes in figma

### PR DESCRIPTION
**Pull request by chihsuan**
### Changes proposed in this Pull Request:

Closes #1019.

Update all copies from latest changes in figma

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

### Tasks

Figma: lD0gTB4IqGsmSmsnjZNaP6-fi-49%3A7986 | 1EGipzzulCg2uk4MsSf2x7-fi-14%3A5786

1. Choose a WCPay country
1. Go to `WooCommerce > Home > Payments task`
1. Observe that the free trial notice displays: `"Only Administrators and Store Managers can place orders during the free trial. If you are ready to accept payments from customers, [upgrade to a paid plan](URL)".`
1. Confirm the heading is `Get ready to accept payments` 
1. Go to WooCommerce > Home > **Tax task**
1. Observe that the free trial notice displays `"During the free trial period you can configure your sales tax settings, but not collect it. To start selling products, [upgrade now](URL)."`
1. Complete store details, add products tasks and make sure payments task is incomplete
1. Observe that payment task header description is `"Give your customers an easy and convenient way to pay! Set up and test some of our fast and secure online or in person payment methods."`

Payments task fill header

Payments task header description

Tax

### WCPay

Figma: 1EGipzzulCg2uk4MsSf2x7-fi-14%3A7215

1. Change your store country to US
4. Click WooCommerce Payments menu.
5. Confirm the notice shows `"Only Administrators and Store Managers can place orders during the free trial. If you are ready to accept payments from customers, [upgrade to a paid plan](url)."`
6. cd to `/wp-content/plugins/woocommerce-payments` and open `includes/admin/class-wc-payments-admin.php`
7. return false from `maybe_redirect_to_onboarding` method.
8. Set `$should_render_full_menu` variable to true in `add_payments_men` method.
9. Refresh your admin page and you should see the full menu under WooCommerce Payment menu.
10. Go to **Payments > overview screen:**
11. Confirm the notice shows `"Only Administrators and Store Managers can place orders during the free trial. If you are ready to accept payments from customers, [upgrade to a paid plan](URL)."`
12. Go to **Payments > transactions screen:**
13. Confirm the notice shows `"Only Administrators and Store Managers can place orders during the free trial. If you are ready to accept payments from customers, [upgrade to a paid plan](URL)."`
14. Go to **Payments > WCPay deposits screen:**
15. Confirm the notice shows `"Deposits are not available during the trial period. To start processing real transactions and receive payments and payouts, [upgrade to a pain plan](URL)."`

Screenshot 2023-03-03 at 10 50 29
Screenshot 2023-03-03 at 10 53 30
Screenshot 2023-03-03 at 10 53 39

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
LGTM! Thanks @chihsuan 🚀

**Comment by PanosSynetos** [comment]
Hey @chihsuan - I'd like to add a commit in this PR, I have a minor change in one of the texts related to the free trial, and it would be a pity to open a new issue/PR just for this.

I'll have it ready in 10 mins :)

**Comment by chihsuan** [comment]
> Hey @chihsuan - I'd like to add a commit in this PR, I have a minor change in one of the texts related to the free trial, and it would be a pity to open a new issue/PR just for this.
> 
> I'll have it ready in 10 mins :)

Ok 😄

**Review by ilyasfoo — APPROVED** [review]
Looking great, @chihsuan! Thanks for the super quick fix! LGTM 🚢

**Pull request merged**
