### PR TITLE
Add filter for recommended WPCOM themes

### LINKED ISSUE #1316: [Customize Your Store] Filter recommended themes
**Issue Description:**

We have implemented a new API to fetch themes and added a filter `__experimental_woocommerce_rest_get_recommended_themes` for extensibility in https://github.com/woocommerce/woocommerce/pull/40508.

We need to use that filter to provide the correct themes in WooExpress.

### PR DESCRIPTION
**Pull request by crunnells**
### Changes proposed in this Pull Request:

Adds a filter to change the recommended themes for Woo Express sites on WPCOM. 

Closes #1316.

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Follow the instructions to setup a Woo Express site to test CYS: pdibGW-2pG-p2
2. Update the `wc-calypso-bridge` plugin with this branch.
3. Visit `My Home` in `wp-admin` and click "Customize Your Store"
4. The Intro page will show 4 themes; confirm that the site URL is appended to the theme links, eg: `https://wordpress.com/theme/tazza/yourblog.com`
5. Activate one of the recommended themes (Tsubaki, Tazza, Amulet, or Zaino) via the Themes showcase
6. Re-visit the "Customize Your Store" page and confirm that active theme is marked as such:
Screen Shot 2023-10-17 at 2 57 39 PM

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by moon0326 — COMMENTED** [review]
Thank you for working on it 👍 

LGTM and tested well with an ECOM plan. @chihsuan Do we also need to use this filter in trial mode?

**Comment by chihsuan** [comment]
> LGTM and tested well with an ECOM plan. @chihsuan Do we also need to use this filter in trial mode?

Yes. 🙂

**Review by adrianduffell — APPROVED** [review]
LGTM, nice work @crunnells !

**Comment by moon0326** [comment]
@crunnells As confirmed by @chihsuan, we also need to run the hook for free trials. What do you think about creating a new class (e.g., class-wc-calypso-bridge-cys-themes.php) to customize the list for both trial and econ plans? You can include the new class in https://github.com/Automattic/wc-calypso-bridge/blob/master/class-wc-calypso-bridge.php#L100. You can check for free trial plan with [wc_calypso_bridge_is_ecommerce_trial_plan](https://github.com/Automattic/wc-calypso-bridge/blob/master/includes/class-wc-calypso-bridge-ecommerce-admin-menu.php#L34) function.

**Comment by crunnells** [comment]
> As confirmed by @chihsuan, we also need to run the hook for free trials. What do you think about creating a new class (e.g., class-wc-calypso-bridge-cys-themes.php) to customize the list for both trial and econ plans?

Do we restrict which themes free trial accounts can use and activate?

**Comment by moon0326** [comment]
> > As confirmed by @chihsuan, we also need to run the hook for free trials. What do you think about creating a new class (e.g., class-wc-calypso-bridge-cys-themes.php) to customize the list for both trial and econ plans?
> 
> Do we restrict which themes free trial accounts can use and activate?

I don't think we need to restrict the themes. @chihsuan @adrianduffell Could you confirm please?

**Comment by moon0326** [comment]
> @crunnells As confirmed by @chihsuan, we also need to run the hook for free trials. What do you think about creating a new class (e.g., class-wc-calypso-bridge-cys-themes.php) to customize the list for both trial and econ plans? You can include the new class in https://github.com/Automattic/wc-calypso-bridge/blob/master/class-wc-calypso-bridge.php#L100. You can check for free trial plan with [wc_calypso_bridge_is_ecommerce_trial_plan](https://github.com/Automattic/wc-calypso-bridge/blob/master/includes/class-wc-calypso-bridge-ecommerce-admin-menu.php#L34) function.
> 
> @adrianduffell Do you think we have a different (or possibly better) approach?

This is actually not correct. https://github.com/Automattic/wc-calypso-bridge/blob/35bb9b2ad64c324ffe0454d7cbb69a81e7359391/includes/class-wc-calypso-bridge-filters.php#L40 checked for both econ and econ trial plans.

Sorry for the false alarm 🙏

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Comment by chihsuan** [comment]
> I don't think we need to restrict the themes. @chihsuan @adrianduffell Could you confirm please?

Thanks for the ping. We don't need to restrict the themes! 🙂

**Pull request merged**
