### PR TITLE
Free trial: Hide partial tasklist and tasks

### PR DESCRIPTION
**Pull request by chihsuan**
Partially fixes https://github.com/Automattic/wc-calypso-bridge/issues/945

## Changes in this PR

- Hide "Add a domain" (AddDomain) task
- Hide "Get more sales" (Marketing) task
- Hide "Things to do next" tasklist

## Test instructions

1. Make sure to copy over the latest changes in [woocmmerce-calypso-bridge-helper.php](https://gist.github.com/moon0326/cac46c70a2cee81b61faef517fef7178) and the plugin is activated.
2. Change [this line](https://gist.github.com/moon0326/cac46c70a2cee81b61faef517fef7178#file-a-woocommerce-calypso-bridge-helper-php-L33) to false in your local env. This forces your env to have free trial.
3. Go to WooCommerce > Home
4. Confirm domain, marketing task, and "Things to do next" tasklist are hidden

Screenshot 2023-02-16 at 10 17 09

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
Tested well, LGTM! 🚢

**Review by rjchow — APPROVED** [review]
Works correctly, looks good! Thanks!

**Comment by FlorianBru** [comment]
Hey all, just curious was there a specific business reason behind hiding the 'add a domain task'?

**Comment by ilyasfoo** [comment]
Hey @FlorianBru, it was done in mistake since the old design does not have the domain task and I missed checking figma for the latest change:

image

**Pull request merged**
