### PR TITLE
Move "composer/installers" package to require-dev.

### PR DESCRIPTION
**Pull request by mreishus**
### Changes proposed in this Pull Request:

I found that wpcomsh was shipping with a large number of installer files in vendor and in the classmap:

These don't look relevant to anything we need to do. Tracing it down, this dependency was added here when adding linting commands to the repo: https://github.com/Automattic/wc-calypso-bridge/pull/90

It might have also been added here instead: https://github.com/Automattic/wc-calypso-bridge/pull/90/commits/a9a44f436235e2963c31ef1adecfc66924b7d095

As far as I can tell, `composer/installers` lets you install plugins to places other than `vendor/`, but I don't see it being used here. @anomiex also ran into some issues from it being included here: https://github.com/Automattic/jetpack/pull/37737#discussion_r1629784758

I think that means this is only needed for development (if at all), and we don't need to be including this when shipping the plugin. I searched for instances of "installer" and don't see it being used anywhere.

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by ivan-ottinger — COMMENTED** [review]
Hey, @mreishus. 👋🏼 I am probably not the most suitable person to judge the change proposed in this PR so will let it for others.

Thanks for the review request anyways!

**Comment by obenland** [comment]
@Automattic/somewherewarm Could you help with a review for this PR?

**Review by chihsuan — APPROVED** [review]
LGTM. 👍  I did a quick test on a E-commerce plan site and all seems to be working fine. Thanks for the PR. @mreishus

**Comment by PanosSynetos** [comment]
Hey @obenland - SomewhereWarm hasn't worked with Calypso Bridge for over six months. Someone that is using Calypso Bridge on a daily basis, should be better suited to test this on out.

**Review by ilyasfoo — APPROVED** [review]
Thanks for reviewing, @chihsuan! 

@mreishus Apologies to have missed this earlier. I've also tested this change in a business and a ecommerce plan site. I'm unsure how to fully test the change, but what I did was:

1. In a fresh clone, run `npm install`, `composer install`, and `npm run build` and observed no related error message
2. Upload the entire directory to `wp-content/mu-plugins/wpcomsh/vendor/automattic/wc-calypso-bridge` of the site
3. Tested wp-admin and frontend and observed no error
4. Looked at `wp php-errors` and observed no error
5. Looked at `wp-content/debug.log` and observed no error

I've also updated the changelog in 23f91b7.

LGTM, feel free to merge. Let me know if you need help with deploying

**Comment by mreishus** [comment]
Thanks for the review! Created deploy PR #1526

**Pull request merged**
