### PR TITLE
Change store on wpcom order link to /wp-admin/post.php

### LINKED ISSUE #649: Change new order notification email order link to `/wp-admin` from `/store`
## Description 

The new order notification email currently contains a link to `/store/order`

Since Store is deprecated and will soon be removed, we should update the implementation so that the `/wp-admin/post.php?post=` path is always used, which will bring users to the WooCommerce Core experience to view the order.

Source code: https://github.com/Automattic/wc-calypso-bridge/blob/master/store-on-wpcom/inc/wc-calypso-bridge-email-order-url.php

## Screenshots

[Order #43] should be linked to `/wp-admin/post.php?post=`

Screen Shot 2021-02-17 at 12 01 56 PM

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #649 

This PR removes `woocommerce_get_edit_order_url` filter, which changes edit order URL to WPCOM store link. The order link is now linked to `:store-url/wp-admin/post.php?post=:order-id&action=edit`

This change is needed as we are removing the store from wordpress.com.

### Test Instruction

1. Create a new atomic site at https://mc.a8c.com/atomic/ephemeral-sites/
2. Do not check `wpcomsh` 
3. Checkout this branch and zip it or use the attached zip file.
[wc-calypso-bridge.zip](https://github.com/Automattic/wc-calypso-bridge/files/6025700/wc-calypso-bridge.zip)

4. Upload the zip file to your atomic site and activate it
5. Add a new product
6. Open a new incognito browser window and place a new order
7. Check your email and confirm the link

#### Screenshots

Screen Shot 2021-02-18 at 10 09 34 PM copy

### CODE REVIEW

**Review by timmyc — CHANGES_REQUESTED** [review]
Great catch finding this one Moon. The code looks like it should work well to me, but I followed the test instructions, and with the .zip file attatched installed on my atomic site, I'm getting the following error in the log, and I'm unable to place an order:

```
2021-02-22T20:45:10+00:00 CRITICAL Uncaught Error: Call to undefined function write_log() in /srv/htdocs/wp-content/plugins/wc-calypso-bridge/store-on-wpcom/inc/wc-calypso-bridge-email-order-url.php:21
Stack trace:
#0 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): wc_calypso_bridge_email_get_wpcom_order_link('https://ephemer...', Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 /srv/htdocs/__wp__/wp-includes/plugin.php(212): WP_Hook->apply_filters('https://ephemer...', Array)
#2 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(1668): apply_filters('woocommerce_get...', 'https://ephemer...', Object(Automattic\WooCommerce\Admin\Overrides\Order))
#3 /srv/htdocs/wp-content/plugins/woocommerce/templates/emails/email-order-details.php(27): WC_Order->get_edit_order_url()
#4 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')
#5 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-emails.php(421): wc_get_template('emails/email-or...', Array)
#6 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): WC_Emails->order_details(Object(Automattic\WooCommerce\Admin\Overrides\Order), true, false, Object(WC_Email_New_Order))
#7 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#8 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#9 /srv/htdocs/wp-content/plugins/woocommerce/templates/emails/admin-new-order.php(35): do_action('woocommerce_ema...', Object(Automattic\WooCommerce\Admin\Overrides\Order), true, false, Object(WC_Email_New_Order))
#10 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')
#11 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(364): wc_get_template('emails/admin-ne...', Array, '', '')
#12 /srv/htdocs/wp-content/plugins/woocommerce/includes/emails/class-wc-email-new-order.php(133): wc_get_template_html('emails/admin-ne...', Array)
#13 /srv/htdocs/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(541): WC_Email_New_Order->get_content_html()
#14 /srv/htdocs/wp-content/plugins/woocommerce/includes/emails/class-wc-email-new-order.php(110): WC_Email->get_content()
#15 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): WC_Email_New_Order->trigger(15, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#16 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#17 /srv/htdocs/__wp__/wp-includes/plugin.php(551): WP_Hook->do_action(Array)
#18 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-emails.php(170): do_action_ref_array('woocommerce_ord...', Array)
#19 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): WC_Emails::send_transactional_email(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#20 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#21 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#22 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(372): do_action('woocommerce_ord...', 15, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#23 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(221): WC_Order->status_transition()
#24 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(333): WC_Order->save()
#25 /srv/htdocs/wp-content/plugins/woocommerce/includes/gateways/cod/class-wc-gateway-cod.php(326): WC_Order->update_status('processing', 'Payment to be m...')
#26 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(959): WC_Gateway_COD->process_payment(15)
#27 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1171): WC_Checkout->process_order_payment(15, 'cod')
#28 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(465): WC_Checkout->process_checkout()
#29 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): WC_AJAX::checkout('')
#30 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#31 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#32 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action('wc_ajax_checkou...')
#33 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): WC_AJAX::do_wc_ajax('')
#34 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(false, Array)
#35 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#36 /srv/htdocs/__wp__/wp-includes/template-loader.php(13): do_action('template_redire...')
#37 /srv/htdocs/__wp__/wp-blog-header.php(19): require_once('/srv/htdocs/__w...')
#38 /srv/htdocs/__wp__/index.php(17): require('/srv/htdocs/__w...')
#39 {main}
  thrown in /srv/htdocs/wp-content/plugins/wc-calypso-bridge/store-on-wpcom/inc/wc-calypso-bridge-email-order-url.php on line 21
```

**Comment by moon0326** [comment]
> Great catch finding this one Moon. The code looks like it should work well to me, but I followed the test instructions, and with the .zip file attatched installed on my atomic site, I'm getting the following error in the log, and I'm unable to place an order:
> 
> ```
> 2021-02-22T20:45:10+00:00 CRITICAL Uncaught Error: Call to undefined function write_log() in /srv/htdocs/wp-content/plugins/wc-calypso-bridge/store-on-wpcom/inc/wc-calypso-bridge-email-order-url.php:21
> Stack trace:
> #0 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): wc_calypso_bridge_email_get_wpcom_order_link('https://ephemer...', Object(Automattic\WooCommerce\Admin\Overrides\Order))
> #1 /srv/htdocs/__wp__/wp-includes/plugin.php(212): WP_Hook->apply_filters('https://ephemer...', Array)
> #2 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(1668): apply_filters('woocommerce_get...', 'https://ephemer...', Object(Automattic\WooCommerce\Admin\Overrides\Order))
> #3 /srv/htdocs/wp-content/plugins/woocommerce/templates/emails/email-order-details.php(27): WC_Order->get_edit_order_url()
> #4 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')
> #5 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-emails.php(421): wc_get_template('emails/email-or...', Array)
> #6 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): WC_Emails->order_details(Object(Automattic\WooCommerce\Admin\Overrides\Order), true, false, Object(WC_Email_New_Order))
> #7 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> #8 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
> #9 /srv/htdocs/wp-content/plugins/woocommerce/templates/emails/admin-new-order.php(35): do_action('woocommerce_ema...', Object(Automattic\WooCommerce\Admin\Overrides\Order), true, false, Object(WC_Email_New_Order))
> #10 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')
> #11 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(364): wc_get_template('emails/admin-ne...', Array, '', '')
> #12 /srv/htdocs/wp-content/plugins/woocommerce/includes/emails/class-wc-email-new-order.php(133): wc_get_template_html('emails/admin-ne...', Array)
> #13 /srv/htdocs/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(541): WC_Email_New_Order->get_content_html()
> #14 /srv/htdocs/wp-content/plugins/woocommerce/includes/emails/class-wc-email-new-order.php(110): WC_Email->get_content()
> #15 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): WC_Email_New_Order->trigger(15, Object(Automattic\WooCommerce\Admin\Overrides\Order))
> #16 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> #17 /srv/htdocs/__wp__/wp-includes/plugin.php(551): WP_Hook->do_action(Array)
> #18 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-emails.php(170): do_action_ref_array('woocommerce_ord...', Array)
> #19 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): WC_Emails::send_transactional_email(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order))
> #20 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> #21 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
> #22 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(372): do_action('woocommerce_ord...', 15, Object(Automattic\WooCommerce\Admin\Overrides\Order))
> #23 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(221): WC_Order->status_transition()
> #24 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(333): WC_Order->save()
> #25 /srv/htdocs/wp-content/plugins/woocommerce/includes/gateways/cod/class-wc-gateway-cod.php(326): WC_Order->update_status('processing', 'Payment to be m...')
> #26 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(959): WC_Gateway_COD->process_payment(15)
> #27 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1171): WC_Checkout->process_order_payment(15, 'cod')
> #28 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(465): WC_Checkout->process_checkout()
> #29 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): WC_AJAX::checkout('')
> #30 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> #31 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
> #32 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action('wc_ajax_checkou...')
> #33 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(287): WC_AJAX::do_wc_ajax('')
> #34 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(false, Array)
> #35 /srv/htdocs/__wp__/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
> #36 /srv/htdocs/__wp__/wp-includes/template-loader.php(13): do_action('template_redire...')
> #37 /srv/htdocs/__wp__/wp-blog-header.php(19): require_once('/srv/htdocs/__w...')
> #38 /srv/htdocs/__wp__/index.php(17): require('/srv/htdocs/__w...')
> #39 {main}
>   thrown in /srv/htdocs/wp-content/plugins/wc-calypso-bridge/store-on-wpcom/inc/wc-calypso-bridge-email-order-url.php on line 21
> ```

🤦 My bad. I zipped a different directory. I've updated the zip file 👍

**Comment by mattsherman** [comment]
@moon0326 I still get the same error, with what I believe is the updated zip file.

**Comment by mattsherman** [comment]
@moon0326 Hrmm.... actually, I didn't have the updated zip file. With the updated zip file, I no longer get an error. The order is placed (I see it in wp-admin), but the front-end checkout page doesn't change, and I don't get any e-mail.

**Comment by moon0326** [comment]
> @moon0326 Hrmm.... actually, I didn't have the updated zip file. With the updated zip file, I no longer get an error. The order is placed (I see it in wp-admin), but the front-end checkout page doesn't change, and I don't get any e-mail.

Try checking the spam box. I noticed that almost all my test emails go to the spam box with `Sender address rejected: 451 (in
    reply to RCPT TO comman` error.

**Review by timmyc — APPROVED** [review]
The last zip worked for me, and I also unpacked the zip to verify the changes were there. Placed a test order, and confirmed the email had the link pointed back to wp-admin.

**Pull request merged**
