### PR TITLE
add travis configuration

### LINKED ISSUE #531: [Test] Configure Repo with CI and Create Test for ecomm/store
In order to improve the quality of the experience in the ecommerce plan, we need to begin implementing test coverage for the functionality implemented within the Calypso Bridge plugin. There is a test suite now with only example assertions, so for this issue, let's create a test that asserts the proper set of logic is loaded for both scenarios:

- Assert the proper code path is taken for ecomm plan sites
- Assert the proper code is executed for Store on WPCOM sites.

Lastly we need to setup CI on this repository to run the test suite against each branch.

### PR DESCRIPTION
**Pull request by rrennick**
See #531 

This PR adds the Travis configuration and scripts to automated unit & CS testing. The tests folder currently has a sample passing test.

### CODE REVIEW

**Comment by timmyc** [comment]
@rrennick super silly question but how do I run the test suite locally? When I go to run it I'm still getting the following:

```
➜  wc-calypso-bridge git:(fix/531) phpunit
Error: Looks like you're using PHPUnit 8.0.6. WordPress is currently only compatible with PHPUnit up to 7.x.
Please use the latest PHPUnit version from the 7.x branch.
```

**Comment by rrennick** [comment]
> how do I run the test suite locally?

@timmyc run `composer install` then `./vendor/bin/phpunit`. That will use the version set in `composer.json`.

**Comment by rrennick** [comment]
@timmyc I just added a commit to this for the file reorg in https://github.com/woocommerce/woocommerce/pull/26345. Can you test phpunit with both WC 4.1 and master?

**Comment by timmyc** [comment]
Okay I tried with 4.1 for .org repo - but `./vendor/bin/phpunit` failed, but checked out master, and all is working well now:

```
vagrant@vvv:/srv/www/ecomm/public_html/wp-content/plugins/wc-calypso-bridge$ ./vendor/bin/phpunit
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Installing WooCommerce...
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.26-1+ubuntu18.04.1+deb.sury.org+1
Configuration: /srv/www/ecomm/public_html/wp-content/plugins/wc-calypso-bridge/phpunit.xml

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 11:
  - Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' is not allowed.

  Test results may not be as expected.


.                                                                   1 / 1 (100%)

Time: 12.1 seconds, Memory: 56.25 MB

OK (1 test, 1 assertion)
```

**Comment by rrennick** [comment]
> Okay I tried with 4.1 for .org repo

You would need the 4.1 tag. The .org version doesn't have the composer files.

**Pull request merged**
