### PR TITLE
Update default progress title

### PR DESCRIPTION
**Pull request by chihsuan**
### Changes proposed in this Pull Request:

Closes https://github.com/Automattic/wp-calypso/issues/74898

Update the default home screen headline for users on the free trial.
figma: lD0gTB4IqGsmSmsnjZNaP6-fi-2157_19583

Screenshot 2023-04-12 at 11 24 53

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Use free trial site
2. Go to `Settings > General` (/wp-admin/options-general.php)
3. Remove Site Title (if it exists)
4. Go to `WooCommerce > Home`
5. Observe that the home screen title renders `Welcome to your Woo Express store`

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by rjchow — APPROVED** [review]
Thanks!

**Review by ilyasfoo — APPROVED** [review]
Tested well, LGTM!

**Comment by ilyasfoo** [comment]
Hey, @chihsuan. Sorry for the late feedback, I just thought about the implementation, it seems we [only override the copy](https://github.com/Automattic/wc-calypso-bridge/blob/8ccdfd663a1dd9cbd10d4b1c06037114906290ec/src/index.js#L121-L124) in free trial sites. If I'm understanding it correctly, the intention is to apply to all WooExpress plans. What do you think?

**Comment by chihsuan** [comment]
@ilyasfoo Confirmed we just need it for free-trial. 🙂 


Screenshot 2023-04-21 at 14 47 32

**Pull request merged**
