### PR TITLE
Revert #1377 and fix init priority to properly hide the empty get more options tab

### LINKED ISSUE #1394: Revert PR 1377 empty Product Data > Get more options tab and improve solution
As discussed with @manospsyx and @jimjasson , let's revert

- #1377 

and improve the solution, by making sure the `woocommerce_allow_marketplace_suggestions` used elsewhere, works properly

### PR DESCRIPTION
**Pull request by PanosSynetos**
### Changes proposed in this Pull Request:

Discussed with @jimjasson about this, and he correctly pointed out that there is race condition.

WooCommerce is hooking class `WC_Marketplace_Suggestions` on `init` on priority 10, and we also hook with priority 10.

We need to lower the priority on our class

Closes #1394  .
- #1394 

### How to test the changes in this Pull Request:

See testing instructions 👇 
- https://github.com/Automattic/wc-calypso-bridge/pull/1377

### Future discussion

Should we treat the same `init` with lower priorities? If so, let's open a new PR to address them

image

### CODE REVIEW

**Review by jimjasson — APPROVED** [review]
I agree 100% with this fix as core also hooks at `init` with priority `10` to add the marketplace suggestions -- we need to hook in sooner to remove them.

**Comment by jimjasson** [comment]
> Should we treat the same init with lower priorities? If so, let's open a new PR to address them

I think that this depends! For example, in this case we were able to identify that core hooks into `init` with priority `10` to add the marketplace suggestions and we were hooking in the same hook with the same priority to remove them. Is this the case for other things we do too? Like the `update_option` you mention in the example -- does core introduce this option at the same hook/priority where we are updating it?

**Comment by PanosSynetos** [comment]
The `update_option` was misleading in my screenshot, sorry - It's not an `add_action`

I'm only referring to the `add_action`. I believe that when we use this practice to add an `add_action` in the constructor, hooked on `init`, it needs to be really early in priority.

Then the rest of the `add_action` , `add_filter` inside the init function, should have their own priority (ideally really late, PHP_INT_MAX)

I'm not saying that's the only way going forward, it's a discussion. Looking forward for @xristos3490  point of view (even @manospsyx if/when he gets a chance)


```php
	private function __construct() {
...
		add_action( 'init', array( $this, 'init' ), 1 );
	}

	public function init() {
...
		add_filter( 'woocommerce_data_stores', array( $this, 'filter_notes_data_store' ), 100 );
		add_action( 'admin_head', array( $this, 'hide_alerts_on_non_settings_pages' ) );
		add_filter( 'woocommerce_helper_suppress_connect_notice', '__return_true' );
		add_filter( 'woocommerce_show_admin_notice', '__return_false' );
		add_filter( 'woocommerce_allow_marketplace_suggestions', '__return_false' );
	}
```

**Review by xristos3490 — APPROVED** [review]
Changes are looking safe. Approved!🤞 

Regarding this subject:
> Should we treat the same init with lower priorities? If so, let's open a new PR to address them

I'd opt to keep them as is, until there is a reason to change them.

**Pull request merged**
