### PR TITLE
Introduce an Inbox allow-list and welcome/domain messages for the WooX free trial plan

### LINKED ISSUE #1267: Introduce Inbox message allow-list for the Free Trial plan and update existing block-list
### Description

The primary goal of this task is to introduce a allow-list to only display Inbox messages relevant to new merchants who have signed up for the Woo Express Free Trial plan.

As part of this work, we will:

- Identify relevant messages appearing in the Inbox during the first 2 weeks of a new merchant's journey.
- Introduce a filter to allow-list those messages and suppress all other communication.
- Share suggestions with owning teams and/or implement rules to suppress irrelevant messages beyond the Free Trial period.

Additionally, the existing block-list will be updated based on the findings of the recently conducted Inbox audit.

Important:

- RINs meant to reach Free Trial / Woo Express sites should continue to do so (be allow-listed).
- Ensure that essential maintenance notices in Woo Core are allow-listed (e.g. database upgrade, other?).

### LINKED ISSUE #1338: Introduce a Welcome message in the Free Trial Inbox
### Description

The goal of this task is to display a Welcome message in the the Inbox of new Free Trial sites. The message content will be consistent with the content of the welcome email, which is sent as part of the lifecycle email series.

### LINKED ISSUE #1339: Introduce domain purchase Inbox message in the Free Trial Inbox
### Description

The goal here is to introduce a domain purchase message in the the Inbox of new Woo Express sites. The message content will be consistent with the content of the corresponding lifecycle email. 

The message will be added on sites that have existed for at least 24 hours, if a domain has not already been purchased.

### PR DESCRIPTION
**Pull request by manospsyx**
### Changes proposed in this Pull Request:

- Introduced an Inbox allow-list for Free Trial plan users.
- Updated the existing messages/notes block-list based on the findings of our recent Inbox audit.
- Added a welcome message consistent with the welcome email sent as part of the lifecycle series.
- Added a domain purchase message/prompt.
- Removed the block-based Cart/Checkout Inbox note.

Closes #1267, closes #1338, closes #1339

#### Allow-listed Messages

```
// Woo Core.
'wc-admin-add-first-product-note',
'wc-admin-mobile-app',
'wc-admin-test-checkout',
'wc-admin-payments-remind-me-later',
'wc-admin-onboarding-payments-reminder',
'wc-admin-orders-milestone',
// Woo Express lifeycle messages.
'wc-calypso-bridge-free-trial-welcome',
'wc-calypso-bridge-free-trial-choose-domain',
// Extensions.
'stripe-apple-pay-domain-verification-needed'
```

In addition to these messages, all [Remote Inbox messages targeting Woo Express](https://github.com/woocommerce/woocommerce/pull/40513) are allowed. 

#### Suppressed Messages

```
// Woo Core.
'wc-admin-adding-and-managing-products',
'wc-admin-choosing-a-theme',
'wc-admin-launch-checklist',
'wc-admin-personalize-store',
'wc-admin-customizing-product-catalog',
'wc-admin-first-product',
'wc-admin-store-notice-giving-feedback-2',
'wc-admin-insight-first-product-and-payment',
'wc-admin-insight-first-sale',
'wc-admin-install-jp-and-wcs-plugins',
'wc-admin-manage-store-activity-from-home-screen',
'wc-admin-usage-tracking-opt-in',
'wc-admin-remove-unsecured-report-files',
'wc-admin-update-store-details',
'wc-admin-welcome-to-woocommerce-for-store-users',
'wc-admin-woocommerce-payments',
'wc-payments-notes-set-up-refund-policy',
'wc-admin-marketing-jetpack-backup',
'wc-admin-migrate-from-shopify', // suppress for now, to be revisited.
'wc-admin-magento-migration', // suppress for now, to be revisited.
'wc-admin-woocommerce-subscriptions', // suppress for now, to be revisited.
'wc-admin-online-clothing-store', // suppress for now, to be revisited.
'wc-admin-selling-online-courses', // suppress for now, to be revisited.
// Extensions.
'gla-invalid-php-version',
'gla-64-bit',
'gla-wc-admin',
'gla-wc-requirement',
'facebook-for-woocommerce-settings-moved-to-marketing',
'wc-payments-notes-set-up-stripe-link',
'wc-pb-bulk-discounts',
'wc-prl-whats-new-1-4',
'automatewoo-system-checks',
'automatewoo-php-minimum-version-check',
'automatewoo-wc-minimum-version-check',
'automatewoo-welcome-notification',
'automatewoo-subscriptions-addon-deactivated',
'automatewoo-update',
```

Note that, with this PR, both Inbox and Notice type notes/messages will be suppressed, unless added to the allow-list ("notice" type notes are similar to admin notices and meant to appear on WooCommerce page only).

#### Allow/Block-listing Implementation

Until this PR, the display of Inbox messages was suppressed at the DB read phase. This is problematic as:

- Once a suppressed message appears (e.g. after updating to a paid plan), it will appear back-dated.
- For the reason above, the order of messages in the Inbox will be wrong: New messages may appear before messages that the user has already read, resulting in a confusing experience.

This PR resolves this by overriding the `admin-note` data store with a new one that prevents new messages from being saved on the DB unless the allow/block-listing logic allows that to happen.

#### CC Block Inbox Note

This PR also removes the block-based Cart/Checkout Inbox note: The purpose of the note was to inform new users that the block-based checkout may not work with some third-party Extensions. I find this defensiveness unnecessary at the whole point of Woo Express is to give users a collection of tools that work together, and 3PDs should support the block-based checkout at this point.

#### Welcome Message
Screenshot 2023-08-14 at 5 30 04 PM

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

#### Woo Express Plan

1. Create a Woo Express Free Trial site.
2. Confirm that the only message showing up in the Inbox is a Welcome message.
3. Confirm that Inbox messages that are not included in the allow-list do not appear.

And:

1. Create a Performance plan site.
2. Confirm that suppressed Inbox messages do not appear.
3. Confirm that the welcome message does not appear.

#### Other Plans

1. Create a Business plan site with WooCommerce.
2. Confirm that the welcome message does not appear.
3. Confirm that Woo Inbox messages are not suppressed in any way.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?

### FOR PR REVIEWER ONLY:

-   [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by manospsyx** [comment]
### Issue 

Preventing the display of Inbox messages at the DB read phase is problematic as:

Once a suppressed message appears (e.g. after updating to a paid plan), it will appear back-dated.
For the reason above, the order of messages in the Inbox will be wrong: New messages may appear before messages that the user has already read, resulting in a confusing experience.

I will keep looking for a performant solution that prevents messages from being saved in the DB, rather than a solution that relies on modifying the read query.

**Review by xristos3490 — APPROVED** [review]
Looks good! It seems like a very sustainable way of handling the notes-bloat without affecting any existing sites. Nicely done! 

I couldn’t test the provisioning process manually, though I’m not sure if it’s possible. However, it appears safe to me and the logs were clear.

👌

**Comment by manospsyx** [comment]
To do:

- Introduce a back door to allow RIN to reach Free Trial sites (slug substring?).
- Ensure that essential maintenance notices in Woo Core are whitelisted (e.g. database upgrade, other?).

**Review by PanosSynetos — APPROVED** [review]
This has been manually tested and pair reviewed with @manospsyx 

Works as expected - Ready to merge!

**Pull request merged**
